# 这是一个示例 mods.toml 文件。它包含与加载 mod 相关的数据。
# 有几个必填字段 (#mandatory)，以及更多可选字段 (#optional)。
# 整体格式为标准 TOML 格式，v0.5.0。
# 请注意，此文件中有几个 TOML 列表。
# 在此处查找有关 toml 格式的更多信息: https://github.com/toml-lang/toml
# 要加载的 mod loader 类型名称 - 对于常规 FML @Mod mod，应为 javafml
modLoader="javafml" #mandatory
# 与上述 mod loader 匹配的版本范围 - 对于常规 FML @Mod，这将是 forge 版本
loaderVersion="${loader_version_range}" #mandatory 通常由 Forge 在每个 Minecraft 版本中更新。参见我们的下载页面获取版本列表。
# mod 的许可证。这是必填的元数据，有助于更容易理解你的再分发属性。
# 在 https://choosealicense.com/ 查看你的选项。All rights reserved 是默认的版权立场，因此也是此处的默认值。
license="${mod_license}"
# 当 mod 出现问题时，引导人们访问的 URL
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# 如果你的 mod 是纯客户端且没有多人游戏功能（无论是专用服务器还是局域网开放），
# 将其设置为 true，Forge 将为你设置正确的 displayTest 并跳过在专用服务器上加载你的 mod。
#clientSideOnly=true #optional - 默认为 false（若不填写）
# mod 列表 - 此处允许多少个由各个 mod loader 决定
[[mods]] #mandatory
# mod 的 modid
modId="${mod_id}" #mandatory
# mod 的版本号
version="${mod_version}" #mandatory
# mod 的显示名称
displayName="${mod_name}" #mandatory
# 用于查询此 mod 更新的 URL。参见 JSON 更新规范 https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# mod 的"主页" URL，显示在 mod UI 中
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# 包含显示 logo 的文件名（位于 mod JAR 根目录中）
#logoFile="examplemod.png" #optional
# 显示在 mod UI 中的文本字段
#credits="" #optional
# 显示在 mod UI 中的文本字段
authors="${mod_authors}" #optional
# Display Test 控制你的 mod 在服务器连接屏幕上的显示
# MATCH_VERSION 意味着如果客户端和服务器上的版本不同，你的 mod 将导致红色 X。这是默认行为，如果你的 mod 有服务器和客户端元素，应选择此项。
# IGNORE_SERVER_VERSION 意味着如果你的 mod 在服务器上存在但在客户端上不存在，不会导致红色 X。如果你的是纯服务器 mod，应使用此项。
# IGNORE_ALL_VERSION 意味着如果你的 mod 在客户端或服务器上存在，不会导致红色 X。这是一种特殊情况的设置，仅在 mod 没有服务器组件时使用。
# NONE 意味着没有为你的 mod 设置 display test。你需要自行处理，参见 IExtensionPoint.DisplayTest 了解更多信息。你可以使用此值定义任何你想要的方案。
# 重要提示: 这不是关于你的 mod 在哪些环境（CLIENT 或 DEDICATED SERVER）中加载的指令。你的 mod 应在其所在的任何环境中加载（也许什么都不做！）。
#displayTest="MATCH_VERSION" # 如果未指定，当 clientSideOnly=false 时默认为 MATCH_VERSION，当 clientSideOnly=true 时默认为 IGNORE_ALL_VERSION (#optional)

# mod 的描述文本（多行！）(#mandatory)
description='''${mod_description}'''
# 依赖项 - 使用 . 来指示特定 modid 的依赖。依赖项是可选的。
[[dependencies.${mod_id}]] #optional
    # 依赖项的 modid
    modId="forge" #mandatory
    # 此依赖项是否必须存在 - 如果不是，则必须指定下面的排序
    mandatory=true #mandatory
    # 依赖项的版本范围
    versionRange="${forge_version_range}" #mandatory
    # 依赖项的排序关系 - 如果依赖项不是必填的，则需要指定 BEFORE 或 AFTER
    # BEFORE - 此 mod 在依赖项之前加载
    # AFTER - 此 mod 在依赖项之后加载
    ordering="NONE"
    # 此依赖项适用的侧 - BOTH、CLIENT 或 SERVER
    side="BOTH"
# 以下是另一个依赖项
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    # 此版本范围声明了最低为当前 minecraft 版本，上限到但不包括下一个主版本
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    mandatory=true
    versionRange="[5.14.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.8.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[15.20.0.112,)"
ordering="AFTER"
side="BOTH"

# Features 是游戏环境的特定属性，你可以声明你的 mod 所需的条件。此示例声明
# 你的 mod 需要 GL 3.2 或更高版本。其他 features 将会添加。它们是侧感知的，因此声明此项不会
# 阻止你的 mod 在服务器上加载。
#[features.${mod_id}]
#openGLVersion="[3.2,)"
