package com.pasterdream.pasterdreammod.init;

import com.pasterdream.pasterdreammod.helper.renderhelper.GUIBackGroundRender;
import com.pasterdream.pasterdreammod.world.item.dreamnotesbook.DreamNotesBookRegistry;
import net.minecraft.network.chat.Component;

public class ModDreamNotesBookContentRelation
{
    private static final int CONTENT_START_X = 20;
    private static final int CONTENT_START_Y = 20;
    private static final int CONTENT_FINAL_X = 120;
    private static final int CONTENT_FINAL_Y = 160;

    public static void registerDreamNotesBookContentRelation()
    {
        DreamNotesBookRegistry.register("misty_dreaming_lotus", Component.translatable("book.pasterdream.title.花园解密:迷梦冶梦莲"), "琴雨梦", Component.translatable("book.pasterdream.content.花园解密:迷梦冶梦莲"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("piercing_edel_weiss", Component.translatable("book.pasterdream.title.花园解密:凛冽雪绒花"), "琴雨梦", Component.translatable("book.pasterdream.content.花园解密:凛冽雪绒花"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("golden_fox", Component.translatable("book.pasterdream.title.花园解密:九尾狐"), "琴雨梦", Component.translatable("book.pasterdream.content.花园解密:九尾狐"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("dyedream_travelogue_1", Component.translatable("book.pasterdream.title.染梦游记 其一"), "琴雨梦", Component.translatable("book.pasterdream.content.染梦游记 其一"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("dyedream_travelogue_2", Component.translatable("book.pasterdream.title.染梦游记 其二"), "琴雨梦", Component.translatable("book.pasterdream.content.染梦游记 其二"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("dyedream_travelogue_3", Component.translatable("book.pasterdream.title.染梦游记 其三"), "琴雨梦", Component.translatable("book.pasterdream.content.染梦游记 其三"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("dream_church_1", Component.translatable("book.pasterdream.title.染梦教堂 其一"), "琴雨梦", Component.translatable("book.pasterdream.content.染梦教堂 其一"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("dream_church_2", Component.translatable("book.pasterdream.title.染梦教堂 其二"), "夜岚", Component.translatable("book.pasterdream.content.染梦教堂 其二"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("dream_church_3", Component.translatable("book.pasterdream.title.染梦教堂 其三"), "卡莱", Component.translatable("book.pasterdream.content.染梦教堂 其三"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("dyedream_crystal_ball", Component.translatable("book.pasterdream.title.染梦水晶球"), "琴雨梦", Component.translatable("book.pasterdream.content.染梦水晶球"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("dream_wishing_tree", Component.translatable("book.pasterdream.title.祈愿树"), "琴雨梦", Component.translatable("book.pasterdream.content.祈愿树"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("warm_cold_wind", Component.translatable("book.pasterdream.title.温暖的寒风"), "琴雨梦", Component.translatable("book.pasterdream.content.温暖的寒风"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("pink_agalic_house", Component.translatable("book.pasterdream.title.粉顶蘑菇屋"), "琴雨梦", Component.translatable("book.pasterdream.content.粉顶蘑菇屋"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("melt_dream_liquid_well", Component.translatable("book.pasterdream.title.融梦涌泉井"), "琴雨梦", Component.translatable("book.pasterdream.content.融梦涌泉井"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("floating_island_diary", Component.translatable("book.pasterdream.title.浮空岛日记"), "琴雨梦", Component.translatable("book.pasterdream.content.浮空岛日记"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("falling_leaves_return_to_their_roots_cracked_pods_return_to_their_crowns", Component.translatable("book.pasterdream.title.落叶归根 裂荚归冠"), "琴雨梦", Component.translatable("book.pasterdream.content.落叶归根 裂荚归冠"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("dream_floating", Component.translatable("book.pasterdream.title.梦境漂泊"), "琴雨梦", Component.translatable("book.pasterdream.content.梦境漂泊"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("big_bubble", Component.translatable("book.pasterdream.title.气泡生态球"), "千夜", Component.translatable("book.pasterdream.content.气泡生态球"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("dream_laboratory", Component.translatable("book.pasterdream.title.染梦实验室"), "彗星", Component.translatable("book.pasterdream.content.染梦实验室"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("interacting_with_dream", Component.translatable("book.pasterdream.title.来往于梦"), "流华", Component.translatable("book.pasterdream.content.来往于梦"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("dyedream_world_tree", Component.translatable("book.pasterdream.title.染梦世界树"), "极星", Component.translatable("book.pasterdream.content.染梦世界树"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("wings_of_dai_da_luo_si_and_floating_island", Component.translatable("book.pasterdream.title.代达罗斯之翼与浮空岛"), "极星", Component.translatable("book.pasterdream.content.代达罗斯之翼与浮空岛"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("desert_cottage", Component.translatable("book.pasterdream.title.探求秘辛"), "极星", Component.translatable("book.pasterdream.content.探求秘辛"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("research_notes_black_metal", Component.translatable("book.pasterdream.title.研究笔记:黑金属"), "琴雨梦", Component.translatable("book.pasterdream.content.研究笔记:黑金属"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("lamp_shadow_travelogue_2", Component.translatable("book.pasterdream.title.灯影游记 其二"), "琴雨梦", Component.translatable("book.pasterdream.content.灯影游记 其二"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("shadow_place", Component.translatable("book.pasterdream.title.黑暗之地"), "琴雨梦", Component.translatable("book.pasterdream.content.黑暗之地"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("shadow_fungus_house", Component.translatable("book.pasterdream.title.阴影小木屋"), "极星", Component.translatable("book.pasterdream.content.阴影小木屋"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("shadow_underground_workroom", Component.translatable("book.pasterdream.title.阴影地下工作室"), "极星", Component.translatable("book.pasterdream.content.阴影地下工作室"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("shadow_dyed_sloppy_handwriting_notes", Component.translatable("book.pasterdream.title.>被阴影浸染的字迹潦草的笔记<"), "作者名字模糊不清", Component.translatable("book.pasterdream.content.>被阴影浸染的字迹潦草的笔记<"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("regarding_shadow_hands_essay", Component.translatable("book.pasterdream.title.关于黑暗之手的随笔"), "极星", Component.translatable("book.pasterdream.content.关于黑暗之手的随笔"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("decisive_battle_with_shadow_hands_and_fail", Component.translatable("book.pasterdream.title.与黑色双手的决战和败北"), "千夜", Component.translatable("book.pasterdream.content.与黑色双手的决战和败北"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("wind_break_knight", Component.translatable("book.pasterdream.title.破风的骑士"), "琴雨梦", Component.translatable("book.pasterdream.content.破风的骑士"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
        DreamNotesBookRegistry.register("morning_new_wind", Component.translatable("book.pasterdream.title.清晨的新风"), "琴雨梦", Component.translatable("book.pasterdream.content.清晨的新风"), GUIBackGroundRender.DREAM_NOTES_BOOK, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y);
    }
}
