package com.pasterdream.pasterdreammod.init;

import com.pasterdream.pasterdreammod.helper.renderhelper.GUIBackGroundRender;
import com.pasterdream.pasterdreammod.world.item.dreamnotesbook.DreamNotesBookRegistry;
import net.minecraft.network.chat.Component;

public class ModDreamNotesBookContentRelation
{
    private static final int CONTENT_START_X = 20;
    private static final int CONTENT_START_Y = 20;
    private static final int CONTENT_FINAL_X = 120;
    private static final int CONTENT_FINAL_Y = 170;

    public static void registerDreamNotesBookContentRelation()
    {
        DreamNotesBookRegistry.register("使用说明", Component.translatable("book.pasterdream.title.使用说明"), "2884omgpy", Component.translatable("book.pasterdream.content.使用说明"), GUIBackGroundRender.EMPTY_NOTES, 360, 180, 1, 1, 359, 179, GUIBackGroundRender.USE_GUIDE, 0xFF000000);

        DreamNotesBookRegistry.register("花园解密:迷梦冶梦莲", Component.translatable("book.pasterdream.title.花园解密:迷梦冶梦莲"), "琴雨梦", Component.translatable("book.pasterdream.content.花园解密:迷梦冶梦莲"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("花园解密:凛冽雪绒花", Component.translatable("book.pasterdream.title.花园解密:凛冽雪绒花"), "琴雨梦", Component.translatable("book.pasterdream.content.花园解密:凛冽雪绒花"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("花园解密:九尾狐", Component.translatable("book.pasterdream.title.花园解密:九尾狐"), "琴雨梦", Component.translatable("book.pasterdream.content.花园解密:九尾狐"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("染梦裂隙", Component.translatable("book.pasterdream.title.染梦裂隙"), "琴雨梦", Component.translatable("book.pasterdream.content.染梦裂隙"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("染梦游记 其一", Component.translatable("book.pasterdream.title.染梦游记 其一"), "琴雨梦", Component.translatable("book.pasterdream.content.染梦游记 其一"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("染梦游记 其二", Component.translatable("book.pasterdream.title.染梦游记 其二"), "琴雨梦", Component.translatable("book.pasterdream.content.染梦游记 其二"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("染梦游记 其三", Component.translatable("book.pasterdream.title.染梦游记 其三"), "琴雨梦", Component.translatable("book.pasterdream.content.染梦游记 其三"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("染梦教堂 其一", Component.translatable("book.pasterdream.title.染梦教堂 其一"), "琴雨梦", Component.translatable("book.pasterdream.content.染梦教堂 其一"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("染梦教堂 其二", Component.translatable("book.pasterdream.title.染梦教堂 其二"), "夜岚", Component.translatable("book.pasterdream.content.染梦教堂 其二"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("染梦教堂 其三", Component.translatable("book.pasterdream.title.染梦教堂 其三"), "卡莱", Component.translatable("book.pasterdream.content.染梦教堂 其三"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("染梦水晶球", Component.translatable("book.pasterdream.title.染梦水晶球"), "琴雨梦", Component.translatable("book.pasterdream.content.染梦水晶球"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("祈愿树", Component.translatable("book.pasterdream.title.祈愿树"), "琴雨梦", Component.translatable("book.pasterdream.content.祈愿树"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("温暖的“寒风”", Component.translatable("book.pasterdream.title.温暖的“寒风”"), "琴雨梦", Component.translatable("book.pasterdream.content.温暖的“寒风”"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("粉顶蘑菇屋", Component.translatable("book.pasterdream.title.粉顶蘑菇屋"), "琴雨梦", Component.translatable("book.pasterdream.content.粉顶蘑菇屋"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("融梦涌泉井", Component.translatable("book.pasterdream.title.融梦涌泉井"), "琴雨梦", Component.translatable("book.pasterdream.content.融梦涌泉井"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("浮空岛日记", Component.translatable("book.pasterdream.title.浮空岛日记"), "琴雨梦", Component.translatable("book.pasterdream.content.浮空岛日记"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("落叶归根 裂荚归冠", Component.translatable("book.pasterdream.title.落叶归根 裂荚归冠"), "琴雨梦", Component.translatable("book.pasterdream.content.落叶归根 裂荚归冠"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("梦境漂泊", Component.translatable("book.pasterdream.title.梦境漂泊"), "琴雨梦", Component.translatable("book.pasterdream.content.梦境漂泊"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("气泡生态球", Component.translatable("book.pasterdream.title.气泡生态球"), "千夜", Component.translatable("book.pasterdream.content.气泡生态球"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("染梦实验室", Component.translatable("book.pasterdream.title.染梦实验室"), "彗星", Component.translatable("book.pasterdream.content.染梦实验室"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("来往于梦", Component.translatable("book.pasterdream.title.来往于梦"), "流华", Component.translatable("book.pasterdream.content.来往于梦"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("染梦世界树", Component.translatable("book.pasterdream.title.染梦世界树"), "极星", Component.translatable("book.pasterdream.content.染梦世界树"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("代达罗斯之翼与浮空岛", Component.translatable("book.pasterdream.title.代达罗斯之翼与浮空岛"), "极星", Component.translatable("book.pasterdream.content.代达罗斯之翼与浮空岛"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("星河果冻和浮空岛", Component.translatable("book.pasterdream.title.星河果冻和浮空岛"), "极星", Component.translatable("book.pasterdream.content.星河果冻和浮空岛"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("融梦釜与融梦炼金术", Component.translatable("book.pasterdream.title.融梦釜与融梦炼金术"), "青岚", Component.translatable("book.pasterdream.content.融梦釜与融梦炼金术"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("魔法使的记录-其一", Component.translatable("book.pasterdream.title.魔法使的记录-其一"), "绫苒", Component.translatable("book.pasterdream.content.魔法使的记录-其一"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);

        DreamNotesBookRegistry.register("探求秘辛", Component.translatable("book.pasterdream.title.探求秘辛"), "极星", Component.translatable("book.pasterdream.content.探求秘辛"), GUIBackGroundRender.DREAM_NOTES_BOOK_OVERWORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_OVERWORLD, 0xFF000000);

        DreamNotesBookRegistry.register("研究笔记:黑金属", Component.translatable("book.pasterdream.title.研究笔记:黑金属"), "琴雨梦", Component.translatable("book.pasterdream.content.研究笔记:黑金属"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("灯影游记 其二", Component.translatable("book.pasterdream.title.灯影游记 其二"), "琴雨梦", Component.translatable("book.pasterdream.content.灯影游记 其二"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("黑暗之地", Component.translatable("book.pasterdream.title.黑暗之地"), "琴雨梦", Component.translatable("book.pasterdream.content.黑暗之地"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("阴影小木屋", Component.translatable("book.pasterdream.title.阴影小木屋"), "极星", Component.translatable("book.pasterdream.content.阴影小木屋"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("阴影地下工作室", Component.translatable("book.pasterdream.title.阴影地下工作室"), "极星", Component.translatable("book.pasterdream.content.阴影地下工作室"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("-被阴影浸染的字迹潦草的笔记-",
                Component.translatable("book.pasterdream.title.-被阴影浸染的字迹潦草的笔记-"),
                "作者名字模糊不清",
                Component.translatable("book.pasterdream.content.-被阴影浸染的字迹潦草的笔记-"),
                GUIBackGroundRender.SHADOW_DYED_DREAM_NOTES_BOOK_GUI,
                250, 235, 80, 60, 194, 221,
                GUIBackGroundRender.SHADOW_DYED_DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("关于黑暗之手的随笔", Component.translatable("book.pasterdream.title.关于黑暗之手的随笔"), "极星", Component.translatable("book.pasterdream.content.关于黑暗之手的随笔"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("与黑色双手的决战和败北", Component.translatable("book.pasterdream.title.与黑色双手的决战和败北"), "千夜", Component.translatable("book.pasterdream.content.与黑色双手的决战和败北"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("侵染教堂-黑面", Component.translatable("book.pasterdream.title.侵染教堂-黑面"), "卡莱", Component.translatable("book.pasterdream.content.侵染教堂-黑面"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("侵染教堂-亮面", Component.translatable("book.pasterdream.title.侵染教堂-亮面"), "卡莱", Component.translatable("book.pasterdream.content.侵染教堂-亮面"), GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_DYEDREAM_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("暮影之笼", Component.translatable("book.pasterdream.title.暮影之笼"), "卡莱", Component.translatable("book.pasterdream.content.暮影之笼"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("暗影图书馆", Component.translatable("book.pasterdream.title.暗影图书馆"), "卡莱", Component.translatable("book.pasterdream.content.暗影图书馆"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);

        DreamNotesBookRegistry.register("沉淀阴影",
                Component.translatable("book.pasterdream.title.沉淀阴影"),
                "琴雨梦",
                Component.translatable("book.pasterdream.content.沉淀阴影"),
                GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("灯影游记 其一",
                Component.translatable("book.pasterdream.title.灯影游记 其一"),
                "未署名",
                Component.translatable("book.pasterdream.content.灯影游记 其一"),
                GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("暗影地牢",
                Component.translatable("book.pasterdream.title.暗影地牢"),
                "琴雨梦",
                Component.translatable("book.pasterdream.content.暗影地牢"),
                GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("暗影地牢入口", Component.translatable("book.pasterdream.title.暗影地牢入口"), "卡莱", Component.translatable("book.pasterdream.content.暗影地牢入口"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("欺诈", Component.translatable("book.pasterdream.title.欺诈"), "卡莱", Component.translatable("book.pasterdream.content.欺诈"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("交易", Component.translatable("book.pasterdream.title.交易"), "卡莱", Component.translatable("book.pasterdream.content.交易"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);
        DreamNotesBookRegistry.register("破碎", Component.translatable("book.pasterdream.title.破碎"), "卡莱", Component.translatable("book.pasterdream.content.破碎"), GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_LAMP_SHADOW_WORLD, 0xFFFFFFFF);

        DreamNotesBookRegistry.register("无翼鸟也有展翅的梦", Component.translatable("book.pasterdream.title.无翼鸟也有展翅的梦"), "琴雨梦", Component.translatable("book.pasterdream.content.无翼鸟也有展翅的梦"), GUIBackGroundRender.DREAM_NOTES_BOOK_WIND_JOURNEY_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_WIND_JOURNEY_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("破风的骑士", Component.translatable("book.pasterdream.title.破风的骑士"), "琴雨梦", Component.translatable("book.pasterdream.content.破风的骑士"), GUIBackGroundRender.DREAM_NOTES_BOOK_WIND_JOURNEY_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_WIND_JOURNEY_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("清晨的新风", Component.translatable("book.pasterdream.title.清晨的新风"), "琴雨梦", Component.translatable("book.pasterdream.content.清晨的新风"), GUIBackGroundRender.DREAM_NOTES_BOOK_WIND_JOURNEY_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_WIND_JOURNEY_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("魔法使的记录-其二", Component.translatable("book.pasterdream.title.魔法使的记录-其二"), "绫苒", Component.translatable("book.pasterdream.content.魔法使的记录-其二"), GUIBackGroundRender.DREAM_NOTES_BOOK_WIND_JOURNEY_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_WIND_JOURNEY_WORLD, 0xFF000000);
        DreamNotesBookRegistry.register("空岛的圣诞树", Component.translatable("book.pasterdream.title.空岛的圣诞树"), "绫苒", Component.translatable("book.pasterdream.content.空岛的圣诞树"), GUIBackGroundRender.DREAM_NOTES_BOOK_WIND_JOURNEY_WORLD_GUI, 140, 180, CONTENT_START_X, CONTENT_START_Y, CONTENT_FINAL_X, CONTENT_FINAL_Y, GUIBackGroundRender.DREAM_NOTES_BOOK_WIND_JOURNEY_WORLD, 0xFF000000);
    }
}
