
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.pasterdream.init;

import net.pasterdream.block.WorkshopGrindBlock;
import net.pasterdream.block.WorkshopCauldeonBlock;
import net.pasterdream.block.WorkshopBlastBlock;
import net.pasterdream.block.WorkshopAnvilBlock;
import net.pasterdream.block.WindrunnerCrystalOreBlock;
import net.pasterdream.block.WindrunnerCrystalBlockBlock;
import net.pasterdream.block.WindmoorWoodBlock;
import net.pasterdream.block.WindmoorTrapdoorBlock;
import net.pasterdream.block.WindmoorStairsBlock;
import net.pasterdream.block.WindmoorSlabBlock;
import net.pasterdream.block.WindmoorPressurePlateBlock;
import net.pasterdream.block.WindmoorPlanksBlock;
import net.pasterdream.block.WindmoorLogBlock;
import net.pasterdream.block.WindmoorLeaves2Block;
import net.pasterdream.block.WindmoorLeaves1Block;
import net.pasterdream.block.WindmoorLeaves0Block;
import net.pasterdream.block.WindmoorFenceGateBlock;
import net.pasterdream.block.WindmoorFenceBlock;
import net.pasterdream.block.WindmoorDoorBlock;
import net.pasterdream.block.WindmoorCrateBlock;
import net.pasterdream.block.WindmoorButtonBlock;
import net.pasterdream.block.WindironBarsBlock;
import net.pasterdream.block.WindKnightSpawnblock4Block;
import net.pasterdream.block.WindKnightSpawnblock3Block;
import net.pasterdream.block.WindKnightSpawnblock2Block;
import net.pasterdream.block.WindKnightSpawnblock1Block;
import net.pasterdream.block.WindKnightSpawnblock0Block;
import net.pasterdream.block.WindIronBlockBlock;
import net.pasterdream.block.WhiteSandBlock;
import net.pasterdream.block.WeaponWorkshopBlock;
import net.pasterdream.block.WeaponTableBlock;
import net.pasterdream.block.Vine0Block;
import net.pasterdream.block.UuzDoll0Block;
import net.pasterdream.block.TwilightLanternBlock;
import net.pasterdream.block.TrueShadowBedBlock;
import net.pasterdream.block.TitaniumOreBlock;
import net.pasterdream.block.TitaniumBlockBlock;
import net.pasterdream.block.ThickShadowBlockBlock;
import net.pasterdream.block.ThickCloudBlock;
import net.pasterdream.block.TheEndlessBookOfDreamSeekersBlock;
import net.pasterdream.block.StructureBlock9Block;
import net.pasterdream.block.StructureBlock8Block;
import net.pasterdream.block.StructureBlock7Block;
import net.pasterdream.block.StructureBlock6Block;
import net.pasterdream.block.StructureBlock5Block;
import net.pasterdream.block.StructureBlock4Block;
import net.pasterdream.block.StructureBlock3Block;
import net.pasterdream.block.StructureBlock2Block;
import net.pasterdream.block.StructureBlock23Block;
import net.pasterdream.block.StructureBlock22Block;
import net.pasterdream.block.StructureBlock21Block;
import net.pasterdream.block.StructureBlock20Block;
import net.pasterdream.block.StructureBlock1Block;
import net.pasterdream.block.StructureBlock19Block;
import net.pasterdream.block.StructureBlock18Block;
import net.pasterdream.block.StructureBlock17Block;
import net.pasterdream.block.StructureBlock16Block;
import net.pasterdream.block.StructureBlock15Block;
import net.pasterdream.block.StructureBlock14Block;
import net.pasterdream.block.StructureBlock13Block;
import net.pasterdream.block.StructureBlock12Block;
import net.pasterdream.block.StructureBlock11Block;
import net.pasterdream.block.StructureBlock10Block;
import net.pasterdream.block.StructureBlock0Block;
import net.pasterdream.block.StrippedWindmoorWoodBlock;
import net.pasterdream.block.StrippedWindmoorLogBlock;
import net.pasterdream.block.StrippedShadowStemBlock;
import net.pasterdream.block.StrippedShadowHyphaeBlock;
import net.pasterdream.block.StarcallCrackBlock;
import net.pasterdream.block.StarcallBlockBlock;
import net.pasterdream.block.SoulOreBlock;
import net.pasterdream.block.SmoothDyedreamquartzBlockBlock;
import net.pasterdream.block.SmallStoneSpiritBlockBlock;
import net.pasterdream.block.Shadowshelf3Block;
import net.pasterdream.block.Shadowshelf2Block;
import net.pasterdream.block.Shadowshelf1Block;
import net.pasterdream.block.Shadowshelf0Block;
import net.pasterdream.block.Shadowdungeondoor3Block;
import net.pasterdream.block.Shadowdungeondoor2Block;
import net.pasterdream.block.ShadowcandleBlock;
import net.pasterdream.block.ShadowWartBlockBlock;
import net.pasterdream.block.ShadowVortexBlock;
import net.pasterdream.block.ShadowTrap0Block;
import net.pasterdream.block.ShadowStoneTilesWallBlock;
import net.pasterdream.block.ShadowStoneTilesStairsBlock;
import net.pasterdream.block.ShadowStoneTilesSlabBlock;
import net.pasterdream.block.ShadowStoneTilesBlock;
import net.pasterdream.block.ShadowStoneBricksWallBlock;
import net.pasterdream.block.ShadowStoneBricksStairsBlock;
import net.pasterdream.block.ShadowStoneBricksSlabBlock;
import net.pasterdream.block.ShadowStoneBricksBlock;
import net.pasterdream.block.ShadowStoneBrickWallBlock;
import net.pasterdream.block.ShadowStoneBrickStairsBlock;
import net.pasterdream.block.ShadowStoneBrickSlabBlock;
import net.pasterdream.block.ShadowStoneBrickBlock;
import net.pasterdream.block.ShadowStoneBlock;
import net.pasterdream.block.ShadowStemBlock;
import net.pasterdream.block.ShadowShroomlightBlock;
import net.pasterdream.block.ShadowPlanksTrapdoorBlock;
import net.pasterdream.block.ShadowPlanksStairsBlock;
import net.pasterdream.block.ShadowPlanksSlabBlock;
import net.pasterdream.block.ShadowPlanksPressurePlateBlock;
import net.pasterdream.block.ShadowPlanksPaneBlock;
import net.pasterdream.block.ShadowPlanksFencegateBlock;
import net.pasterdream.block.ShadowPlanksFenceBlock;
import net.pasterdream.block.ShadowPlanksDoorBlock;
import net.pasterdream.block.ShadowPlanksButtonBlock;
import net.pasterdream.block.ShadowPlanksBlock;
import net.pasterdream.block.ShadowNyliumBlock;
import net.pasterdream.block.ShadowLiquidBlock;
import net.pasterdream.block.ShadowLight0Block;
import net.pasterdream.block.ShadowHyphaeBlock;
import net.pasterdream.block.ShadowFungusBlock;
import net.pasterdream.block.ShadowFissure5Block;
import net.pasterdream.block.ShadowFissure4Block;
import net.pasterdream.block.ShadowFissure3Block;
import net.pasterdream.block.ShadowFissure2Block;
import net.pasterdream.block.ShadowFissure1Block;
import net.pasterdream.block.ShadowFissure0Block;
import net.pasterdream.block.ShadowDungeonPortalBlock;
import net.pasterdream.block.ShadowDungeonKey1Block;
import net.pasterdream.block.ShadowDungeonKey0Block;
import net.pasterdream.block.ShadowDungeonDoor1Block;
import net.pasterdream.block.ShadowDungeonDoor0Block;
import net.pasterdream.block.ShadowDungeonBlock6Block;
import net.pasterdream.block.ShadowDungeonBlock5Block;
import net.pasterdream.block.ShadowDungeonBlock4Block;
import net.pasterdream.block.ShadowDungeonBlock3Block;
import net.pasterdream.block.ShadowDungeonBlock2Block;
import net.pasterdream.block.ShadowDungeonBlock1Block;
import net.pasterdream.block.ShadowDungeonBlock0Block;
import net.pasterdream.block.ShadowDeskBlock;
import net.pasterdream.block.ShadowChestBlock;
import net.pasterdream.block.ShadowBrazierBlock;
import net.pasterdream.block.ShadowBlockBlock;
import net.pasterdream.block.ShadowBlastFurnaceCoreBlock;
import net.pasterdream.block.ShadowBlastFurnaceBlock;
import net.pasterdream.block.ShadowBedBlock;
import net.pasterdream.block.ShadowArenaBlock0Block;
import net.pasterdream.block.SaltBlockBlock;
import net.pasterdream.block.RustBlackMetalBlockWallBlock;
import net.pasterdream.block.RustBlackMetalBlockBlock;
import net.pasterdream.block.RustBlackMetalBlockBarsBlock;
import net.pasterdream.block.RestrainmoveBlockBlock;
import net.pasterdream.block.ResearchTableBlock;
import net.pasterdream.block.RawTitaniumBlockBlock;
import net.pasterdream.block.QymDoll0Block;
import net.pasterdream.block.PolishedCalciteWallBlock;
import net.pasterdream.block.PolishedCalciteStairsBlock;
import net.pasterdream.block.PolishedCalciteSlabBlock;
import net.pasterdream.block.PolishedCalciteBlock;
import net.pasterdream.block.PinkslimeBlockBlock;
import net.pasterdream.block.Pinkagaric3Block;
import net.pasterdream.block.Pinkagaric2Block;
import net.pasterdream.block.Pinkagaric1Block;
import net.pasterdream.block.Pinkagaric0Block;
import net.pasterdream.block.PillarDyedreamquartzBlockBlock;
import net.pasterdream.block.PicnicBasketBlock;
import net.pasterdream.block.Pebble0Block;
import net.pasterdream.block.MossyCyanStoneBricksBlock;
import net.pasterdream.block.MossyCyanStoneBrickWallBlock;
import net.pasterdream.block.MossyCyanStoneBrickStairsBlock;
import net.pasterdream.block.MossyCyanStoneBrickSlabBlock;
import net.pasterdream.block.MoltengoldOreBlock;
import net.pasterdream.block.MoltengoldBlockBlock;
import net.pasterdream.block.MementoItem11Block;
import net.pasterdream.block.MeltdreamLiquidBlock;
import net.pasterdream.block.MeltdreamChestOpenBlock;
import net.pasterdream.block.MeltdreamChestBlock;
import net.pasterdream.block.LostSwordBlockBlock;
import net.pasterdream.block.LooseShadowDungeonBlockBlock;
import net.pasterdream.block.LightballBlock;
import net.pasterdream.block.LightFireflyGlassJarBlock;
import net.pasterdream.block.LifeCrystalBlock;
import net.pasterdream.block.JungleSporePlantBlock;
import net.pasterdream.block.IcestoneBlock;
import net.pasterdream.block.IceBud0Block;
import net.pasterdream.block.GuardCrystalBlock;
import net.pasterdream.block.GuardBlockBlock;
import net.pasterdream.block.Grass9Block;
import net.pasterdream.block.Grass8Block;
import net.pasterdream.block.Grass7Block;
import net.pasterdream.block.Grass6Block;
import net.pasterdream.block.Grass5Block;
import net.pasterdream.block.Grass4Block;
import net.pasterdream.block.Grass3Block;
import net.pasterdream.block.Grass2Block;
import net.pasterdream.block.Grass1Block;
import net.pasterdream.block.Grass15Block;
import net.pasterdream.block.Grass14Block;
import net.pasterdream.block.Grass13Block;
import net.pasterdream.block.Grass12Block;
import net.pasterdream.block.Grass11Block;
import net.pasterdream.block.Grass10Block;
import net.pasterdream.block.GoldenrodBlock;
import net.pasterdream.block.GoldenFoxSculptureBlock;
import net.pasterdream.block.GoldCarveDyedreamGlasspaneBlock;
import net.pasterdream.block.GoldCarveDyedreamGlassBlock;
import net.pasterdream.block.FrameClarityGlasspaneBlock;
import net.pasterdream.block.FrameClarityGlassBlock;
import net.pasterdream.block.FourleafCloverBlock;
import net.pasterdream.block.ForcedTowerBlock;
import net.pasterdream.block.Flower9Block;
import net.pasterdream.block.Flower8Block;
import net.pasterdream.block.Flower7Block;
import net.pasterdream.block.Flower6Block;
import net.pasterdream.block.Flower5Block;
import net.pasterdream.block.Flower3Block;
import net.pasterdream.block.Flower2Block;
import net.pasterdream.block.Flower1Block;
import net.pasterdream.block.Flower18Block;
import net.pasterdream.block.Flower17Block;
import net.pasterdream.block.Flower16Block;
import net.pasterdream.block.Flower15Block;
import net.pasterdream.block.Flower14Block;
import net.pasterdream.block.Flower13Block;
import net.pasterdream.block.Flower12Block;
import net.pasterdream.block.Flower11Block;
import net.pasterdream.block.Flower10Block;
import net.pasterdream.block.FireflyNestBlock;
import net.pasterdream.block.FireflyGlassJarBlock;
import net.pasterdream.block.FigVineBlock;
import net.pasterdream.block.EjectionPressurePlateBlock;
import net.pasterdream.block.EjectionPressureBlockBlock;
import net.pasterdream.block.EcologyGlassJarBlock;
import net.pasterdream.block.DyedreamquartzOreBlock;
import net.pasterdream.block.DyedreamquartzBlockWallBlock;
import net.pasterdream.block.DyedreamquartzBlockStairsBlock;
import net.pasterdream.block.DyedreamquartzBlockSlabBlock;
import net.pasterdream.block.DyedreamquartzBlockBlock;
import net.pasterdream.block.DyedreamdustOreBlock;
import net.pasterdream.block.DyedreamWorldtreeLeavesBlock;
import net.pasterdream.block.DyedreamWoodBlock;
import net.pasterdream.block.DyedreamSeagrassBlock;
import net.pasterdream.block.DyedreamSaplingBlock;
import net.pasterdream.block.DyedreamSandBlock;
import net.pasterdream.block.DyedreamPlanksTrapdoorBlock;
import net.pasterdream.block.DyedreamPlanksStairsBlock;
import net.pasterdream.block.DyedreamPlanksSlabBlock;
import net.pasterdream.block.DyedreamPlanksPressurePlateBlock;
import net.pasterdream.block.DyedreamPlanksPaneBlock;
import net.pasterdream.block.DyedreamPlanksFencegateBlock;
import net.pasterdream.block.DyedreamPlanksFenceBlock;
import net.pasterdream.block.DyedreamPlanksDoorBlock;
import net.pasterdream.block.DyedreamPlanksButtonBlock;
import net.pasterdream.block.DyedreamPlanksBlock;
import net.pasterdream.block.DyedreamPackedIceBlock;
import net.pasterdream.block.DyedreamLotusBlock;
import net.pasterdream.block.DyedreamLogBlock;
import net.pasterdream.block.DyedreamLilyPadBlock;
import net.pasterdream.block.DyedreamLeavesBlock;
import net.pasterdream.block.DyedreamLarternBlock;
import net.pasterdream.block.DyedreamIceBlock;
import net.pasterdream.block.DyedreamGrassBlock;
import net.pasterdream.block.DyedreamGlasspaneBlock;
import net.pasterdream.block.DyedreamGlassBlock;
import net.pasterdream.block.DyedreamDirtBlock;
import net.pasterdream.block.DyedreamDeskBlock;
import net.pasterdream.block.DyedreamCrackBlock;
import net.pasterdream.block.DyedreamBudWallBlock;
import net.pasterdream.block.DyedreamBudStairsBlock;
import net.pasterdream.block.DyedreamBudSlabBlock;
import net.pasterdream.block.DyedreamBudBlockBlock;
import net.pasterdream.block.DyedreamBud2Block;
import net.pasterdream.block.DyedreamBud1Block;
import net.pasterdream.block.DyedreamBud0Block;
import net.pasterdream.block.DyedreamBlockBlock;
import net.pasterdream.block.DreamTrainStructureBlock;
import net.pasterdream.block.DreamSpawner1Block;
import net.pasterdream.block.DreamSpawner0Block;
import net.pasterdream.block.DreamCauldronBlock;
import net.pasterdream.block.DreamAccumulatorBlock;
import net.pasterdream.block.DesertHeroTombBlock;
import net.pasterdream.block.DeepslateTitaniumOreBlock;
import net.pasterdream.block.DarkCloudBlock;
import net.pasterdream.block.CyanStonePressurePlateBlock;
import net.pasterdream.block.CyanStonePillarBlock;
import net.pasterdream.block.CyanStoneButtonBlock;
import net.pasterdream.block.CyanStoneBricksBlock;
import net.pasterdream.block.CyanStoneBrickWallBlock;
import net.pasterdream.block.CyanStoneBrickStairsBlock;
import net.pasterdream.block.CyanStoneBrickSlabBlock;
import net.pasterdream.block.CyanStoneBlock;
import net.pasterdream.block.CyanMossStoneBlock;
import net.pasterdream.block.Crop4bBlock;
import net.pasterdream.block.Crop4aBlock;
import net.pasterdream.block.Crop3bBlock;
import net.pasterdream.block.Crop3aBlock;
import net.pasterdream.block.Crop2bBlock;
import net.pasterdream.block.Crop2aBlock;
import net.pasterdream.block.Crop1bBlock;
import net.pasterdream.block.Crop1aBlock;
import net.pasterdream.block.Crop0bBlock;
import net.pasterdream.block.Crop0aBlock;
import net.pasterdream.block.CrackedShadowStoneBrickBlock;
import net.pasterdream.block.CongealWindOreBlock;
import net.pasterdream.block.CongealWindBlockBlock;
import net.pasterdream.block.CloudBlock;
import net.pasterdream.block.Claypan2Block;
import net.pasterdream.block.Claypan1Block;
import net.pasterdream.block.Claypan0Block;
import net.pasterdream.block.ClayPot0Block;
import net.pasterdream.block.ClarityGlasspaneBlock;
import net.pasterdream.block.ClarityGlassBlock;
import net.pasterdream.block.ChristmasLightsBlock;
import net.pasterdream.block.ChiseledShadowStoneBrickBlock;
import net.pasterdream.block.ChiseledDyedreamquartzBlockBlock;
import net.pasterdream.block.ChiseledCyanStoneBricksBlock;
import net.pasterdream.block.ChargedAmethystBlockBlock;
import net.pasterdream.block.CarveDyedreamGlasspaneBlock;
import net.pasterdream.block.CarveDyedreamGlassBlock;
import net.pasterdream.block.CarveClarityGlasspaneBlock;
import net.pasterdream.block.CarveClarityGlassBlock;
import net.pasterdream.block.CalleCardBlockBlock;
import net.pasterdream.block.CalciteTilesWallBlock;
import net.pasterdream.block.CalciteTilesStairsBlock;
import net.pasterdream.block.CalciteTilesSlabBlock;
import net.pasterdream.block.CalciteTilesBlock;
import net.pasterdream.block.BrokenShadowDungeonProtalBlock;
import net.pasterdream.block.BricksDyedreamquartzBlockBlock;
import net.pasterdream.block.BreakwindCurtainBlock;
import net.pasterdream.block.BlackmetalBlockBlock;
import net.pasterdream.block.BirdsNestBlock;
import net.pasterdream.block.BigBubbleBlock;
import net.pasterdream.block.ArmorWreckBlock4Block;
import net.pasterdream.block.ArmorWreckBlock3Block;
import net.pasterdream.block.ArmorWreckBlock2Block;
import net.pasterdream.block.ArmorWreckBlock1Block;
import net.pasterdream.block.ArmorWreckBlock0Block;
import net.pasterdream.block.AngelBlockBlock;
import net.pasterdream.block.AmberCandyOreBlock;
import net.pasterdream.block.AaroncoshandspawnblockBlock;
import net.pasterdream.block.AaroncosHandChestBlock;
import net.pasterdream.block.AaroncosArenaPortalsBlock;
import net.pasterdream.PasterdreamMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

public class PasterdreamModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, PasterdreamMod.MODID);
	public static final RegistryObject<Block> LIGHTBALL = REGISTRY.register("lightball", () -> new LightballBlock());
	public static final RegistryObject<Block> PEBBLE_0 = REGISTRY.register("pebble_0", () -> new Pebble0Block());
	public static final RegistryObject<Block> MELTDREAM_LIQUID = REGISTRY.register("meltdream_liquid", () -> new MeltdreamLiquidBlock());
	public static final RegistryObject<Block> SHADOW_LIQUID = REGISTRY.register("shadow_liquid", () -> new ShadowLiquidBlock());
	public static final RegistryObject<Block> SHADOWCANDLE = REGISTRY.register("shadowcandle", () -> new ShadowcandleBlock());
	public static final RegistryObject<Block> CLAY_POT_0 = REGISTRY.register("clay_pot_0", () -> new ClayPot0Block());
	public static final RegistryObject<Block> MELTDREAM_CHEST = REGISTRY.register("meltdream_chest", () -> new MeltdreamChestBlock());
	public static final RegistryObject<Block> MELTDREAM_CHEST_OPEN = REGISTRY.register("meltdream_chest_open", () -> new MeltdreamChestOpenBlock());
	public static final RegistryObject<Block> DREAM_ACCUMULATOR = REGISTRY.register("dream_accumulator", () -> new DreamAccumulatorBlock());
	public static final RegistryObject<Block> CLAYPAN_0 = REGISTRY.register("claypan_0", () -> new Claypan0Block());
	public static final RegistryObject<Block> RESEARCH_TABLE = REGISTRY.register("research_table", () -> new ResearchTableBlock());
	public static final RegistryObject<Block> FORCED_TOWER = REGISTRY.register("forced_tower", () -> new ForcedTowerBlock());
	public static final RegistryObject<Block> WEAPON_TABLE = REGISTRY.register("weapon_table", () -> new WeaponTableBlock());
	public static final RegistryObject<Block> WEAPON_WORKSHOP = REGISTRY.register("weapon_workshop", () -> new WeaponWorkshopBlock());
	public static final RegistryObject<Block> DYEDREAM_DESK = REGISTRY.register("dyedream_desk", () -> new DyedreamDeskBlock());
	public static final RegistryObject<Block> LOST_SWORD_BLOCK = REGISTRY.register("lost_sword_block", () -> new LostSwordBlockBlock());
	public static final RegistryObject<Block> DESERT_HERO_TOMB = REGISTRY.register("desert_hero_tomb", () -> new DesertHeroTombBlock());
	public static final RegistryObject<Block> QYM_DOLL_0 = REGISTRY.register("qym_doll_0", () -> new QymDoll0Block());
	public static final RegistryObject<Block> UUZ_DOLL_0 = REGISTRY.register("uuz_doll_0", () -> new UuzDoll0Block());
	public static final RegistryObject<Block> TWILIGHT_LANTERN = REGISTRY.register("twilight_lantern", () -> new TwilightLanternBlock());
	public static final RegistryObject<Block> SHADOW_BED = REGISTRY.register("shadow_bed", () -> new ShadowBedBlock());
	public static final RegistryObject<Block> SHADOW_DESK = REGISTRY.register("shadow_desk", () -> new ShadowDeskBlock());
	public static final RegistryObject<Block> SHADOW_CHEST = REGISTRY.register("shadow_chest", () -> new ShadowChestBlock());
	public static final RegistryObject<Block> SHADOW_BLAST_FURNACE_CORE = REGISTRY.register("shadow_blast_furnace_core", () -> new ShadowBlastFurnaceCoreBlock());
	public static final RegistryObject<Block> SHADOW_BLAST_FURNACE = REGISTRY.register("shadow_blast_furnace", () -> new ShadowBlastFurnaceBlock());
	public static final RegistryObject<Block> CALLE_CARD_BLOCK = REGISTRY.register("calle_card_block", () -> new CalleCardBlockBlock());
	public static final RegistryObject<Block> GUARD_CRYSTAL = REGISTRY.register("guard_crystal", () -> new GuardCrystalBlock());
	public static final RegistryObject<Block> BROKEN_SHADOW_DUNGEON_PROTAL = REGISTRY.register("broken_shadow_dungeon_protal", () -> new BrokenShadowDungeonProtalBlock());
	public static final RegistryObject<Block> SHADOW_DUNGEON_PORTAL = REGISTRY.register("shadow_dungeon_portal", () -> new ShadowDungeonPortalBlock());
	public static final RegistryObject<Block> SHADOW_DUNGEON_DOOR_0 = REGISTRY.register("shadow_dungeon_door_0", () -> new ShadowDungeonDoor0Block());
	public static final RegistryObject<Block> SHADOWDUNGEONDOOR_2 = REGISTRY.register("shadowdungeondoor_2", () -> new Shadowdungeondoor2Block());
	public static final RegistryObject<Block> SHADOW_DUNGEON_KEY_0 = REGISTRY.register("shadow_dungeon_key_0", () -> new ShadowDungeonKey0Block());
	public static final RegistryObject<Block> SHADOW_DUNGEON_KEY_1 = REGISTRY.register("shadow_dungeon_key_1", () -> new ShadowDungeonKey1Block());
	public static final RegistryObject<Block> SHADOW_TRAP_0 = REGISTRY.register("shadow_trap_0", () -> new ShadowTrap0Block());
	public static final RegistryObject<Block> SHADOW_BRAZIER = REGISTRY.register("shadow_brazier", () -> new ShadowBrazierBlock());
	public static final RegistryObject<Block> AARONCOS_HAND_CHEST = REGISTRY.register("aaroncos_hand_chest", () -> new AaroncosHandChestBlock());
	public static final RegistryObject<Block> DREAM_CAULDRON = REGISTRY.register("dream_cauldron", () -> new DreamCauldronBlock());
	public static final RegistryObject<Block> BIRDS_NEST = REGISTRY.register("birds_nest", () -> new BirdsNestBlock());
	public static final RegistryObject<Block> WINDMOOR_CRATE = REGISTRY.register("windmoor_crate", () -> new WindmoorCrateBlock());
	public static final RegistryObject<Block> THE_ENDLESS_BOOK_OF_DREAM_SEEKERS = REGISTRY.register("the_endless_book_of_dream_seekers", () -> new TheEndlessBookOfDreamSeekersBlock());
	public static final RegistryObject<Block> CHRISTMAS_LIGHTS = REGISTRY.register("christmas_lights", () -> new ChristmasLightsBlock());
	public static final RegistryObject<Block> FIREFLY_NEST = REGISTRY.register("firefly_nest", () -> new FireflyNestBlock());
	public static final RegistryObject<Block> ECOLOGY_GLASS_JAR = REGISTRY.register("ecology_glass_jar", () -> new EcologyGlassJarBlock());
	public static final RegistryObject<Block> FIREFLY_GLASS_JAR = REGISTRY.register("firefly_glass_jar", () -> new FireflyGlassJarBlock());
	public static final RegistryObject<Block> LIFE_CRYSTAL = REGISTRY.register("life_crystal", () -> new LifeCrystalBlock());
	public static final RegistryObject<Block> PICNIC_BASKET = REGISTRY.register("picnic_basket", () -> new PicnicBasketBlock());
	public static final RegistryObject<Block> WIND_KNIGHT_SPAWNBLOCK_0 = REGISTRY.register("wind_knight_spawnblock_0", () -> new WindKnightSpawnblock0Block());
	public static final RegistryObject<Block> GOLDEN_FOX_SCULPTURE = REGISTRY.register("golden_fox_sculpture", () -> new GoldenFoxSculptureBlock());
	public static final RegistryObject<Block> DYEDREAM_GRASS = REGISTRY.register("dyedream_grass", () -> new DyedreamGrassBlock());
	public static final RegistryObject<Block> DYEDREAM_DIRT = REGISTRY.register("dyedream_dirt", () -> new DyedreamDirtBlock());
	public static final RegistryObject<Block> DYEDREAM_SAND = REGISTRY.register("dyedream_sand", () -> new DyedreamSandBlock());
	public static final RegistryObject<Block> DYEDREAM_LOG = REGISTRY.register("dyedream_log", () -> new DyedreamLogBlock());
	public static final RegistryObject<Block> DYEDREAM_WOOD = REGISTRY.register("dyedream_wood", () -> new DyedreamWoodBlock());
	public static final RegistryObject<Block> DYEDREAM_LEAVES = REGISTRY.register("dyedream_leaves", () -> new DyedreamLeavesBlock());
	public static final RegistryObject<Block> DYEDREAM_WORLDTREE_LEAVES = REGISTRY.register("dyedream_worldtree_leaves", () -> new DyedreamWorldtreeLeavesBlock());
	public static final RegistryObject<Block> DYEDREAM_PLANKS = REGISTRY.register("dyedream_planks", () -> new DyedreamPlanksBlock());
	public static final RegistryObject<Block> DYEDREAM_PLANKS_STAIRS = REGISTRY.register("dyedream_planks_stairs", () -> new DyedreamPlanksStairsBlock());
	public static final RegistryObject<Block> DYEDREAM_PLANKS_SLAB = REGISTRY.register("dyedream_planks_slab", () -> new DyedreamPlanksSlabBlock());
	public static final RegistryObject<Block> DYEDREAM_PLANKS_FENCE = REGISTRY.register("dyedream_planks_fence", () -> new DyedreamPlanksFenceBlock());
	public static final RegistryObject<Block> DYEDREAM_PLANKS_FENCEGATE = REGISTRY.register("dyedream_planks_fencegate", () -> new DyedreamPlanksFencegateBlock());
	public static final RegistryObject<Block> DYEDREAM_PLANKS_PANE = REGISTRY.register("dyedream_planks_pane", () -> new DyedreamPlanksPaneBlock());
	public static final RegistryObject<Block> DYEDREAM_PLANKS_DOOR = REGISTRY.register("dyedream_planks_door", () -> new DyedreamPlanksDoorBlock());
	public static final RegistryObject<Block> DYEDREAM_PLANKS_TRAPDOOR = REGISTRY.register("dyedream_planks_trapdoor", () -> new DyedreamPlanksTrapdoorBlock());
	public static final RegistryObject<Block> DYEDREAM_PLANKS_PRESSURE_PLATE = REGISTRY.register("dyedream_planks_pressure_plate", () -> new DyedreamPlanksPressurePlateBlock());
	public static final RegistryObject<Block> DYEDREAM_PLANKS_BUTTON = REGISTRY.register("dyedream_planks_button", () -> new DyedreamPlanksButtonBlock());
	public static final RegistryObject<Block> DYEDREAMQUARTZ_ORE = REGISTRY.register("dyedreamquartz_ore", () -> new DyedreamquartzOreBlock());
	public static final RegistryObject<Block> DYEDREAMDUST_ORE = REGISTRY.register("dyedreamdust_ore", () -> new DyedreamdustOreBlock());
	public static final RegistryObject<Block> AMBER_CANDY_ORE = REGISTRY.register("amber_candy_ore", () -> new AmberCandyOreBlock());
	public static final RegistryObject<Block> DYEDREAM_BLOCK = REGISTRY.register("dyedream_block", () -> new DyedreamBlockBlock());
	public static final RegistryObject<Block> PINKSLIME_BLOCK = REGISTRY.register("pinkslime_block", () -> new PinkslimeBlockBlock());
	public static final RegistryObject<Block> PINKAGARIC_0 = REGISTRY.register("pinkagaric_0", () -> new Pinkagaric0Block());
	public static final RegistryObject<Block> PINKAGARIC_1 = REGISTRY.register("pinkagaric_1", () -> new Pinkagaric1Block());
	public static final RegistryObject<Block> PINKAGARIC_2 = REGISTRY.register("pinkagaric_2", () -> new Pinkagaric2Block());
	public static final RegistryObject<Block> PINKAGARIC_3 = REGISTRY.register("pinkagaric_3", () -> new Pinkagaric3Block());
	public static final RegistryObject<Block> DYEDREAM_ICE = REGISTRY.register("dyedream_ice", () -> new DyedreamIceBlock());
	public static final RegistryObject<Block> DYEDREAM_PACKED_ICE = REGISTRY.register("dyedream_packed_ice", () -> new DyedreamPackedIceBlock());
	public static final RegistryObject<Block> BIG_BUBBLE = REGISTRY.register("big_bubble", () -> new BigBubbleBlock());
	public static final RegistryObject<Block> DYEDREAMQUARTZ_BLOCK = REGISTRY.register("dyedreamquartz_block", () -> new DyedreamquartzBlockBlock());
	public static final RegistryObject<Block> SMOOTH_DYEDREAMQUARTZ_BLOCK = REGISTRY.register("smooth_dyedreamquartz_block", () -> new SmoothDyedreamquartzBlockBlock());
	public static final RegistryObject<Block> BRICKS_DYEDREAMQUARTZ_BLOCK = REGISTRY.register("bricks_dyedreamquartz_block", () -> new BricksDyedreamquartzBlockBlock());
	public static final RegistryObject<Block> PILLAR_DYEDREAMQUARTZ_BLOCK = REGISTRY.register("pillar_dyedreamquartz_block", () -> new PillarDyedreamquartzBlockBlock());
	public static final RegistryObject<Block> CHISELED_DYEDREAMQUARTZ_BLOCK = REGISTRY.register("chiseled_dyedreamquartz_block", () -> new ChiseledDyedreamquartzBlockBlock());
	public static final RegistryObject<Block> DYEDREAMQUARTZ_BLOCK_STAIRS = REGISTRY.register("dyedreamquartz_block_stairs", () -> new DyedreamquartzBlockStairsBlock());
	public static final RegistryObject<Block> DYEDREAMQUARTZ_BLOCK_SLAB = REGISTRY.register("dyedreamquartz_block_slab", () -> new DyedreamquartzBlockSlabBlock());
	public static final RegistryObject<Block> DYEDREAMQUARTZ_BLOCK_WALL = REGISTRY.register("dyedreamquartz_block_wall", () -> new DyedreamquartzBlockWallBlock());
	public static final RegistryObject<Block> DYEDREAM_LARTERN = REGISTRY.register("dyedream_lartern", () -> new DyedreamLarternBlock());
	public static final RegistryObject<Block> DYEDREAM_GLASS = REGISTRY.register("dyedream_glass", () -> new DyedreamGlassBlock());
	public static final RegistryObject<Block> DYEDREAM_GLASSPANE = REGISTRY.register("dyedream_glasspane", () -> new DyedreamGlasspaneBlock());
	public static final RegistryObject<Block> CARVE_DYEDREAM_GLASS = REGISTRY.register("carve_dyedream_glass", () -> new CarveDyedreamGlassBlock());
	public static final RegistryObject<Block> CARVE_DYEDREAM_GLASSPANE = REGISTRY.register("carve_dyedream_glasspane", () -> new CarveDyedreamGlasspaneBlock());
	public static final RegistryObject<Block> GOLD_CARVE_DYEDREAM_GLASS = REGISTRY.register("gold_carve_dyedream_glass", () -> new GoldCarveDyedreamGlassBlock());
	public static final RegistryObject<Block> GOLD_CARVE_DYEDREAM_GLASSPANE = REGISTRY.register("gold_carve_dyedream_glasspane", () -> new GoldCarveDyedreamGlasspaneBlock());
	public static final RegistryObject<Block> DYEDREAM_BUD_0 = REGISTRY.register("dyedream_bud_0", () -> new DyedreamBud0Block());
	public static final RegistryObject<Block> DYEDREAM_BUD_1 = REGISTRY.register("dyedream_bud_1", () -> new DyedreamBud1Block());
	public static final RegistryObject<Block> DYEDREAM_BUD_2 = REGISTRY.register("dyedream_bud_2", () -> new DyedreamBud2Block());
	public static final RegistryObject<Block> DYEDREAM_BUD_BLOCK = REGISTRY.register("dyedream_bud_block", () -> new DyedreamBudBlockBlock());
	public static final RegistryObject<Block> DYEDREAM_BUD_STAIRS = REGISTRY.register("dyedream_bud_stairs", () -> new DyedreamBudStairsBlock());
	public static final RegistryObject<Block> DYEDREAM_BUD_SLAB = REGISTRY.register("dyedream_bud_slab", () -> new DyedreamBudSlabBlock());
	public static final RegistryObject<Block> DYEDREAM_BUD_WALL = REGISTRY.register("dyedream_bud_wall", () -> new DyedreamBudWallBlock());
	public static final RegistryObject<Block> ICESTONE = REGISTRY.register("icestone", () -> new IcestoneBlock());
	public static final RegistryObject<Block> ICE_BUD_0 = REGISTRY.register("ice_bud_0", () -> new IceBud0Block());
	public static final RegistryObject<Block> CLOUD = REGISTRY.register("cloud", () -> new CloudBlock());
	public static final RegistryObject<Block> DARK_CLOUD = REGISTRY.register("dark_cloud", () -> new DarkCloudBlock());
	public static final RegistryObject<Block> POLISHED_CALCITE = REGISTRY.register("polished_calcite", () -> new PolishedCalciteBlock());
	public static final RegistryObject<Block> POLISHED_CALCITE_STAIRS = REGISTRY.register("polished_calcite_stairs", () -> new PolishedCalciteStairsBlock());
	public static final RegistryObject<Block> POLISHED_CALCITE_SLAB = REGISTRY.register("polished_calcite_slab", () -> new PolishedCalciteSlabBlock());
	public static final RegistryObject<Block> POLISHED_CALCITE_WALL = REGISTRY.register("polished_calcite_wall", () -> new PolishedCalciteWallBlock());
	public static final RegistryObject<Block> CALCITE_TILES = REGISTRY.register("calcite_tiles", () -> new CalciteTilesBlock());
	public static final RegistryObject<Block> CALCITE_TILES_STAIRS = REGISTRY.register("calcite_tiles_stairs", () -> new CalciteTilesStairsBlock());
	public static final RegistryObject<Block> CALCITE_TILES_SLAB = REGISTRY.register("calcite_tiles_slab", () -> new CalciteTilesSlabBlock());
	public static final RegistryObject<Block> CALCITE_TILES_WALL = REGISTRY.register("calcite_tiles_wall", () -> new CalciteTilesWallBlock());
	public static final RegistryObject<Block> TITANIUM_ORE = REGISTRY.register("titanium_ore", () -> new TitaniumOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_TITANIUM_ORE = REGISTRY.register("deepslate_titanium_ore", () -> new DeepslateTitaniumOreBlock());
	public static final RegistryObject<Block> MOLTENGOLD_ORE = REGISTRY.register("moltengold_ore", () -> new MoltengoldOreBlock());
	public static final RegistryObject<Block> SOUL_ORE = REGISTRY.register("soul_ore", () -> new SoulOreBlock());
	public static final RegistryObject<Block> RAW_TITANIUM_BLOCK = REGISTRY.register("raw_titanium_block", () -> new RawTitaniumBlockBlock());
	public static final RegistryObject<Block> SALT_BLOCK = REGISTRY.register("salt_block", () -> new SaltBlockBlock());
	public static final RegistryObject<Block> TITANIUM_BLOCK = REGISTRY.register("titanium_block", () -> new TitaniumBlockBlock());
	public static final RegistryObject<Block> MOLTENGOLD_BLOCK = REGISTRY.register("moltengold_block", () -> new MoltengoldBlockBlock());
	public static final RegistryObject<Block> CHARGED_AMETHYST_BLOCK = REGISTRY.register("charged_amethyst_block", () -> new ChargedAmethystBlockBlock());
	public static final RegistryObject<Block> SHADOW_BLOCK = REGISTRY.register("shadow_block", () -> new ShadowBlockBlock());
	public static final RegistryObject<Block> THICK_SHADOW_BLOCK = REGISTRY.register("thick_shadow_block", () -> new ThickShadowBlockBlock());
	public static final RegistryObject<Block> SHADOW_STONE = REGISTRY.register("shadow_stone", () -> new ShadowStoneBlock());
	public static final RegistryObject<Block> SHADOW_STONE_BRICK = REGISTRY.register("shadow_stone_brick", () -> new ShadowStoneBrickBlock());
	public static final RegistryObject<Block> SHADOW_STONE_BRICK_STAIRS = REGISTRY.register("shadow_stone_brick_stairs", () -> new ShadowStoneBrickStairsBlock());
	public static final RegistryObject<Block> SHADOW_STONE_BRICK_WALL = REGISTRY.register("shadow_stone_brick_wall", () -> new ShadowStoneBrickWallBlock());
	public static final RegistryObject<Block> SHADOW_STONE_BRICK_SLAB = REGISTRY.register("shadow_stone_brick_slab", () -> new ShadowStoneBrickSlabBlock());
	public static final RegistryObject<Block> SHADOW_STONE_BRICKS = REGISTRY.register("shadow_stone_bricks", () -> new ShadowStoneBricksBlock());
	public static final RegistryObject<Block> SHADOW_STONE_BRICKS_STAIRS = REGISTRY.register("shadow_stone_bricks_stairs", () -> new ShadowStoneBricksStairsBlock());
	public static final RegistryObject<Block> SHADOW_STONE_BRICKS_SLAB = REGISTRY.register("shadow_stone_bricks_slab", () -> new ShadowStoneBricksSlabBlock());
	public static final RegistryObject<Block> SHADOW_STONE_BRICKS_WALL = REGISTRY.register("shadow_stone_bricks_wall", () -> new ShadowStoneBricksWallBlock());
	public static final RegistryObject<Block> SHADOW_STONE_TILES = REGISTRY.register("shadow_stone_tiles", () -> new ShadowStoneTilesBlock());
	public static final RegistryObject<Block> SHADOW_STONE_TILES_STAIRS = REGISTRY.register("shadow_stone_tiles_stairs", () -> new ShadowStoneTilesStairsBlock());
	public static final RegistryObject<Block> SHADOW_STONE_TILES_SLAB = REGISTRY.register("shadow_stone_tiles_slab", () -> new ShadowStoneTilesSlabBlock());
	public static final RegistryObject<Block> SHADOW_STONE_TILES_WALL = REGISTRY.register("shadow_stone_tiles_wall", () -> new ShadowStoneTilesWallBlock());
	public static final RegistryObject<Block> CRACKED_SHADOW_STONE_BRICK = REGISTRY.register("cracked_shadow_stone_brick", () -> new CrackedShadowStoneBrickBlock());
	public static final RegistryObject<Block> CHISELED_SHADOW_STONE_BRICK = REGISTRY.register("chiseled_shadow_stone_brick", () -> new ChiseledShadowStoneBrickBlock());
	public static final RegistryObject<Block> SHADOW_LIGHT_0 = REGISTRY.register("shadow_light_0", () -> new ShadowLight0Block());
	public static final RegistryObject<Block> SHADOW_SHROOMLIGHT = REGISTRY.register("shadow_shroomlight", () -> new ShadowShroomlightBlock());
	public static final RegistryObject<Block> SHADOW_NYLIUM = REGISTRY.register("shadow_nylium", () -> new ShadowNyliumBlock());
	public static final RegistryObject<Block> SHADOW_WART_BLOCK = REGISTRY.register("shadow_wart_block", () -> new ShadowWartBlockBlock());
	public static final RegistryObject<Block> SHADOW_STEM = REGISTRY.register("shadow_stem", () -> new ShadowStemBlock());
	public static final RegistryObject<Block> SHADOW_HYPHAE = REGISTRY.register("shadow_hyphae", () -> new ShadowHyphaeBlock());
	public static final RegistryObject<Block> STRIPPED_SHADOW_STEM = REGISTRY.register("stripped_shadow_stem", () -> new StrippedShadowStemBlock());
	public static final RegistryObject<Block> STRIPPED_SHADOW_HYPHAE = REGISTRY.register("stripped_shadow_hyphae", () -> new StrippedShadowHyphaeBlock());
	public static final RegistryObject<Block> SHADOW_PLANKS = REGISTRY.register("shadow_planks", () -> new ShadowPlanksBlock());
	public static final RegistryObject<Block> SHADOW_PLANKS_STAIRS = REGISTRY.register("shadow_planks_stairs", () -> new ShadowPlanksStairsBlock());
	public static final RegistryObject<Block> SHADOW_PLANKS_SLAB = REGISTRY.register("shadow_planks_slab", () -> new ShadowPlanksSlabBlock());
	public static final RegistryObject<Block> SHADOW_PLANKS_FENCE = REGISTRY.register("shadow_planks_fence", () -> new ShadowPlanksFenceBlock());
	public static final RegistryObject<Block> SHADOW_PLANKS_FENCEGATE = REGISTRY.register("shadow_planks_fencegate", () -> new ShadowPlanksFencegateBlock());
	public static final RegistryObject<Block> SHADOW_PLANKS_PANE = REGISTRY.register("shadow_planks_pane", () -> new ShadowPlanksPaneBlock());
	public static final RegistryObject<Block> SHADOW_PLANKS_DOOR = REGISTRY.register("shadow_planks_door", () -> new ShadowPlanksDoorBlock());
	public static final RegistryObject<Block> SHADOW_PLANKS_TRAPDOOR = REGISTRY.register("shadow_planks_trapdoor", () -> new ShadowPlanksTrapdoorBlock());
	public static final RegistryObject<Block> SHADOW_PLANKS_PRESSURE_PLATE = REGISTRY.register("shadow_planks_pressure_plate", () -> new ShadowPlanksPressurePlateBlock());
	public static final RegistryObject<Block> SHADOW_PLANKS_BUTTON = REGISTRY.register("shadow_planks_button", () -> new ShadowPlanksButtonBlock());
	public static final RegistryObject<Block> RUST_BLACK_METAL_BLOCK = REGISTRY.register("rust_black_metal_block", () -> new RustBlackMetalBlockBlock());
	public static final RegistryObject<Block> RUST_BLACK_METAL_BLOCK_WALL = REGISTRY.register("rust_black_metal_block_wall", () -> new RustBlackMetalBlockWallBlock());
	public static final RegistryObject<Block> RUST_BLACK_METAL_BLOCK_BARS = REGISTRY.register("rust_black_metal_block_bars", () -> new RustBlackMetalBlockBarsBlock());
	public static final RegistryObject<Block> BLACKMETAL_BLOCK = REGISTRY.register("blackmetal_block", () -> new BlackmetalBlockBlock());
	public static final RegistryObject<Block> ARMOR_WRECK_BLOCK_0 = REGISTRY.register("armor_wreck_block_0", () -> new ArmorWreckBlock0Block());
	public static final RegistryObject<Block> ARMOR_WRECK_BLOCK_1 = REGISTRY.register("armor_wreck_block_1", () -> new ArmorWreckBlock1Block());
	public static final RegistryObject<Block> ARMOR_WRECK_BLOCK_2 = REGISTRY.register("armor_wreck_block_2", () -> new ArmorWreckBlock2Block());
	public static final RegistryObject<Block> ARMOR_WRECK_BLOCK_3 = REGISTRY.register("armor_wreck_block_3", () -> new ArmorWreckBlock3Block());
	public static final RegistryObject<Block> ARMOR_WRECK_BLOCK_4 = REGISTRY.register("armor_wreck_block_4", () -> new ArmorWreckBlock4Block());
	public static final RegistryObject<Block> SHADOW_DUNGEON_BLOCK_0 = REGISTRY.register("shadow_dungeon_block_0", () -> new ShadowDungeonBlock0Block());
	public static final RegistryObject<Block> SHADOW_DUNGEON_BLOCK_1 = REGISTRY.register("shadow_dungeon_block_1", () -> new ShadowDungeonBlock1Block());
	public static final RegistryObject<Block> SHADOW_DUNGEON_BLOCK_2 = REGISTRY.register("shadow_dungeon_block_2", () -> new ShadowDungeonBlock2Block());
	public static final RegistryObject<Block> SHADOW_DUNGEON_BLOCK_3 = REGISTRY.register("shadow_dungeon_block_3", () -> new ShadowDungeonBlock3Block());
	public static final RegistryObject<Block> SHADOW_DUNGEON_BLOCK_4 = REGISTRY.register("shadow_dungeon_block_4", () -> new ShadowDungeonBlock4Block());
	public static final RegistryObject<Block> SHADOW_DUNGEON_BLOCK_5 = REGISTRY.register("shadow_dungeon_block_5", () -> new ShadowDungeonBlock5Block());
	public static final RegistryObject<Block> SHADOW_DUNGEON_BLOCK_6 = REGISTRY.register("shadow_dungeon_block_6", () -> new ShadowDungeonBlock6Block());
	public static final RegistryObject<Block> LOOSE_SHADOW_DUNGEON_BLOCK = REGISTRY.register("loose_shadow_dungeon_block", () -> new LooseShadowDungeonBlockBlock());
	public static final RegistryObject<Block> SHADOWSHELF_0 = REGISTRY.register("shadowshelf_0", () -> new Shadowshelf0Block());
	public static final RegistryObject<Block> SHADOWSHELF_1 = REGISTRY.register("shadowshelf_1", () -> new Shadowshelf1Block());
	public static final RegistryObject<Block> SHADOWSHELF_2 = REGISTRY.register("shadowshelf_2", () -> new Shadowshelf2Block());
	public static final RegistryObject<Block> SHADOWSHELF_3 = REGISTRY.register("shadowshelf_3", () -> new Shadowshelf3Block());
	public static final RegistryObject<Block> SHADOW_ARENA_BLOCK_0 = REGISTRY.register("shadow_arena_block_0", () -> new ShadowArenaBlock0Block());
	public static final RegistryObject<Block> SHADOW_FISSURE_0 = REGISTRY.register("shadow_fissure_0", () -> new ShadowFissure0Block());
	public static final RegistryObject<Block> SHADOW_FISSURE_1 = REGISTRY.register("shadow_fissure_1", () -> new ShadowFissure1Block());
	public static final RegistryObject<Block> SHADOW_FISSURE_2 = REGISTRY.register("shadow_fissure_2", () -> new ShadowFissure2Block());
	public static final RegistryObject<Block> SHADOW_FISSURE_3 = REGISTRY.register("shadow_fissure_3", () -> new ShadowFissure3Block());
	public static final RegistryObject<Block> SHADOW_FISSURE_4 = REGISTRY.register("shadow_fissure_4", () -> new ShadowFissure4Block());
	public static final RegistryObject<Block> SHADOW_FISSURE_5 = REGISTRY.register("shadow_fissure_5", () -> new ShadowFissure5Block());
	public static final RegistryObject<Block> CYAN_MOSS_STONE = REGISTRY.register("cyan_moss_stone", () -> new CyanMossStoneBlock());
	public static final RegistryObject<Block> CYAN_STONE = REGISTRY.register("cyan_stone", () -> new CyanStoneBlock());
	public static final RegistryObject<Block> WHITE_SAND = REGISTRY.register("white_sand", () -> new WhiteSandBlock());
	public static final RegistryObject<Block> THICK_CLOUD = REGISTRY.register("thick_cloud", () -> new ThickCloudBlock());
	public static final RegistryObject<Block> WINDMOOR_LOG = REGISTRY.register("windmoor_log", () -> new WindmoorLogBlock());
	public static final RegistryObject<Block> WINDMOOR_WOOD = REGISTRY.register("windmoor_wood", () -> new WindmoorWoodBlock());
	public static final RegistryObject<Block> WINDMOOR_LEAVES_0 = REGISTRY.register("windmoor_leaves_0", () -> new WindmoorLeaves0Block());
	public static final RegistryObject<Block> WINDMOOR_LEAVES_1 = REGISTRY.register("windmoor_leaves_1", () -> new WindmoorLeaves1Block());
	public static final RegistryObject<Block> WINDMOOR_LEAVES_2 = REGISTRY.register("windmoor_leaves_2", () -> new WindmoorLeaves2Block());
	public static final RegistryObject<Block> CYAN_STONE_BRICKS = REGISTRY.register("cyan_stone_bricks", () -> new CyanStoneBricksBlock());
	public static final RegistryObject<Block> CYAN_STONE_BRICK_STAIRS = REGISTRY.register("cyan_stone_brick_stairs", () -> new CyanStoneBrickStairsBlock());
	public static final RegistryObject<Block> CYAN_STONE_BRICK_SLAB = REGISTRY.register("cyan_stone_brick_slab", () -> new CyanStoneBrickSlabBlock());
	public static final RegistryObject<Block> CYAN_STONE_BRICK_WALL = REGISTRY.register("cyan_stone_brick_wall", () -> new CyanStoneBrickWallBlock());
	public static final RegistryObject<Block> MOSSY_CYAN_STONE_BRICKS = REGISTRY.register("mossy_cyan_stone_bricks", () -> new MossyCyanStoneBricksBlock());
	public static final RegistryObject<Block> MOSSY_CYAN_STONE_BRICK_STAIRS = REGISTRY.register("mossy_cyan_stone_brick_stairs", () -> new MossyCyanStoneBrickStairsBlock());
	public static final RegistryObject<Block> MOSSY_CYAN_STONE_BRICK_SLAB = REGISTRY.register("mossy_cyan_stone_brick_slab", () -> new MossyCyanStoneBrickSlabBlock());
	public static final RegistryObject<Block> MOSSY_CYAN_STONE_BRICK_WALL = REGISTRY.register("mossy_cyan_stone_brick_wall", () -> new MossyCyanStoneBrickWallBlock());
	public static final RegistryObject<Block> CHISELED_CYAN_STONE_BRICKS = REGISTRY.register("chiseled_cyan_stone_bricks", () -> new ChiseledCyanStoneBricksBlock());
	public static final RegistryObject<Block> CYAN_STONE_PILLAR = REGISTRY.register("cyan_stone_pillar", () -> new CyanStonePillarBlock());
	public static final RegistryObject<Block> WINDMOOR_PLANKS = REGISTRY.register("windmoor_planks", () -> new WindmoorPlanksBlock());
	public static final RegistryObject<Block> WINDMOOR_STAIRS = REGISTRY.register("windmoor_stairs", () -> new WindmoorStairsBlock());
	public static final RegistryObject<Block> WINDMOOR_SLAB = REGISTRY.register("windmoor_slab", () -> new WindmoorSlabBlock());
	public static final RegistryObject<Block> WINDMOOR_FENCE = REGISTRY.register("windmoor_fence", () -> new WindmoorFenceBlock());
	public static final RegistryObject<Block> WINDMOOR_FENCE_GATE = REGISTRY.register("windmoor_fence_gate", () -> new WindmoorFenceGateBlock());
	public static final RegistryObject<Block> WINDMOOR_DOOR = REGISTRY.register("windmoor_door", () -> new WindmoorDoorBlock());
	public static final RegistryObject<Block> WINDMOOR_TRAPDOOR = REGISTRY.register("windmoor_trapdoor", () -> new WindmoorTrapdoorBlock());
	public static final RegistryObject<Block> WINDMOOR_PRESSURE_PLATE = REGISTRY.register("windmoor_pressure_plate", () -> new WindmoorPressurePlateBlock());
	public static final RegistryObject<Block> WINDMOOR_BUTTON = REGISTRY.register("windmoor_button", () -> new WindmoorButtonBlock());
	public static final RegistryObject<Block> CYAN_STONE_PRESSURE_PLATE = REGISTRY.register("cyan_stone_pressure_plate", () -> new CyanStonePressurePlateBlock());
	public static final RegistryObject<Block> CYAN_STONE_BUTTON = REGISTRY.register("cyan_stone_button", () -> new CyanStoneButtonBlock());
	public static final RegistryObject<Block> CLARITY_GLASS = REGISTRY.register("clarity_glass", () -> new ClarityGlassBlock());
	public static final RegistryObject<Block> CARVE_CLARITY_GLASS = REGISTRY.register("carve_clarity_glass", () -> new CarveClarityGlassBlock());
	public static final RegistryObject<Block> FRAME_CLARITY_GLASS = REGISTRY.register("frame_clarity_glass", () -> new FrameClarityGlassBlock());
	public static final RegistryObject<Block> CLARITY_GLASSPANE = REGISTRY.register("clarity_glasspane", () -> new ClarityGlasspaneBlock());
	public static final RegistryObject<Block> CARVE_CLARITY_GLASSPANE = REGISTRY.register("carve_clarity_glasspane", () -> new CarveClarityGlasspaneBlock());
	public static final RegistryObject<Block> FRAME_CLARITY_GLASSPANE = REGISTRY.register("frame_clarity_glasspane", () -> new FrameClarityGlasspaneBlock());
	public static final RegistryObject<Block> BREAKWIND_CURTAIN = REGISTRY.register("breakwind_curtain", () -> new BreakwindCurtainBlock());
	public static final RegistryObject<Block> STRIPPED_WINDMOOR_LOG = REGISTRY.register("stripped_windmoor_log", () -> new StrippedWindmoorLogBlock());
	public static final RegistryObject<Block> STRIPPED_WINDMOOR_WOOD = REGISTRY.register("stripped_windmoor_wood", () -> new StrippedWindmoorWoodBlock());
	public static final RegistryObject<Block> WINDRUNNER_CRYSTAL_ORE = REGISTRY.register("windrunner_crystal_ore", () -> new WindrunnerCrystalOreBlock());
	public static final RegistryObject<Block> WINDRUNNER_CRYSTAL_BLOCK = REGISTRY.register("windrunner_crystal_block", () -> new WindrunnerCrystalBlockBlock());
	public static final RegistryObject<Block> CONGEAL_WIND_BLOCK = REGISTRY.register("congeal_wind_block", () -> new CongealWindBlockBlock());
	public static final RegistryObject<Block> CONGEAL_WIND_ORE = REGISTRY.register("congeal_wind_ore", () -> new CongealWindOreBlock());
	public static final RegistryObject<Block> WIND_IRON_BLOCK = REGISTRY.register("wind_iron_block", () -> new WindIronBlockBlock());
	public static final RegistryObject<Block> EJECTION_PRESSURE_PLATE = REGISTRY.register("ejection_pressure_plate", () -> new EjectionPressurePlateBlock());
	public static final RegistryObject<Block> WINDIRON_BARS = REGISTRY.register("windiron_bars", () -> new WindironBarsBlock());
	public static final RegistryObject<Block> EJECTION_PRESSURE_BLOCK = REGISTRY.register("ejection_pressure_block", () -> new EjectionPressureBlockBlock());
	public static final RegistryObject<Block> STARCALL_BLOCK = REGISTRY.register("starcall_block", () -> new StarcallBlockBlock());
	public static final RegistryObject<Block> DYEDREAM_CRACK = REGISTRY.register("dyedream_crack", () -> new DyedreamCrackBlock());
	public static final RegistryObject<Block> STARCALL_CRACK = REGISTRY.register("starcall_crack", () -> new StarcallCrackBlock());
	public static final RegistryObject<Block> GUARD_BLOCK = REGISTRY.register("guard_block", () -> new GuardBlockBlock());
	public static final RegistryObject<Block> RESTRAINMOVE_BLOCK = REGISTRY.register("restrainmove_block", () -> new RestrainmoveBlockBlock());
	public static final RegistryObject<Block> DREAM_SPAWNER_0 = REGISTRY.register("dream_spawner_0", () -> new DreamSpawner0Block());
	public static final RegistryObject<Block> DREAM_SPAWNER_1 = REGISTRY.register("dream_spawner_1", () -> new DreamSpawner1Block());
	public static final RegistryObject<Block> SHADOW_VORTEX = REGISTRY.register("shadow_vortex", () -> new ShadowVortexBlock());
	public static final RegistryObject<Block> AARONCOS_ARENA_PORTALS = REGISTRY.register("aaroncos_arena_portals", () -> new AaroncosArenaPortalsBlock());
	public static final RegistryObject<Block> WORKSHOP_CAULDEON = REGISTRY.register("workshop_cauldeon", () -> new WorkshopCauldeonBlock());
	public static final RegistryObject<Block> WORKSHOP_BLAST = REGISTRY.register("workshop_blast", () -> new WorkshopBlastBlock());
	public static final RegistryObject<Block> WORKSHOP_ANVIL = REGISTRY.register("workshop_anvil", () -> new WorkshopAnvilBlock());
	public static final RegistryObject<Block> WORKSHOP_GRIND = REGISTRY.register("workshop_grind", () -> new WorkshopGrindBlock());
	public static final RegistryObject<Block> DYEDREAM_SAPLING = REGISTRY.register("dyedream_sapling", () -> new DyedreamSaplingBlock());
	public static final RegistryObject<Block> CROP_0A = REGISTRY.register("crop_0a", () -> new Crop0aBlock());
	public static final RegistryObject<Block> CROP_0B = REGISTRY.register("crop_0b", () -> new Crop0bBlock());
	public static final RegistryObject<Block> CROP_2A = REGISTRY.register("crop_2a", () -> new Crop2aBlock());
	public static final RegistryObject<Block> CROP_2B = REGISTRY.register("crop_2b", () -> new Crop2bBlock());
	public static final RegistryObject<Block> CROP_3A = REGISTRY.register("crop_3a", () -> new Crop3aBlock());
	public static final RegistryObject<Block> CROP_3B = REGISTRY.register("crop_3b", () -> new Crop3bBlock());
	public static final RegistryObject<Block> GRASS_3 = REGISTRY.register("grass_3", () -> new Grass3Block());
	public static final RegistryObject<Block> GRASS_4 = REGISTRY.register("grass_4", () -> new Grass4Block());
	public static final RegistryObject<Block> FLOWER_8 = REGISTRY.register("flower_8", () -> new Flower8Block());
	public static final RegistryObject<Block> FLOWER_10 = REGISTRY.register("flower_10", () -> new Flower10Block());
	public static final RegistryObject<Block> GRASS_5 = REGISTRY.register("grass_5", () -> new Grass5Block());
	public static final RegistryObject<Block> GRASS_6 = REGISTRY.register("grass_6", () -> new Grass6Block());
	public static final RegistryObject<Block> GRASS_7 = REGISTRY.register("grass_7", () -> new Grass7Block());
	public static final RegistryObject<Block> FLOWER_9 = REGISTRY.register("flower_9", () -> new Flower9Block());
	public static final RegistryObject<Block> FLOWER_13 = REGISTRY.register("flower_13", () -> new Flower13Block());
	public static final RegistryObject<Block> FLOWER_14 = REGISTRY.register("flower_14", () -> new Flower14Block());
	public static final RegistryObject<Block> VINE_0 = REGISTRY.register("vine_0", () -> new Vine0Block());
	public static final RegistryObject<Block> DYEDREAM_LILY_PAD = REGISTRY.register("dyedream_lily_pad", () -> new DyedreamLilyPadBlock());
	public static final RegistryObject<Block> DYEDREAM_SEAGRASS = REGISTRY.register("dyedream_seagrass", () -> new DyedreamSeagrassBlock());
	public static final RegistryObject<Block> DYEDREAM_LOTUS = REGISTRY.register("dyedream_lotus", () -> new DyedreamLotusBlock());
	public static final RegistryObject<Block> FLOWER_11 = REGISTRY.register("flower_11", () -> new Flower11Block());
	public static final RegistryObject<Block> FLOWER_12 = REGISTRY.register("flower_12", () -> new Flower12Block());
	public static final RegistryObject<Block> FLOWER_16 = REGISTRY.register("flower_16", () -> new Flower16Block());
	public static final RegistryObject<Block> FLOWER_17 = REGISTRY.register("flower_17", () -> new Flower17Block());
	public static final RegistryObject<Block> CROP_1A = REGISTRY.register("crop_1a", () -> new Crop1aBlock());
	public static final RegistryObject<Block> CROP_1B = REGISTRY.register("crop_1b", () -> new Crop1bBlock());
	public static final RegistryObject<Block> CROP_4A = REGISTRY.register("crop_4a", () -> new Crop4aBlock());
	public static final RegistryObject<Block> CROP_4B = REGISTRY.register("crop_4b", () -> new Crop4bBlock());
	public static final RegistryObject<Block> FLOWER_1 = REGISTRY.register("flower_1", () -> new Flower1Block());
	public static final RegistryObject<Block> FLOWER_2 = REGISTRY.register("flower_2", () -> new Flower2Block());
	public static final RegistryObject<Block> JUNGLE_SPORE_PLANT = REGISTRY.register("jungle_spore_plant", () -> new JungleSporePlantBlock());
	public static final RegistryObject<Block> FLOWER_5 = REGISTRY.register("flower_5", () -> new Flower5Block());
	public static final RegistryObject<Block> GRASS_1 = REGISTRY.register("grass_1", () -> new Grass1Block());
	public static final RegistryObject<Block> FLOWER_3 = REGISTRY.register("flower_3", () -> new Flower3Block());
	public static final RegistryObject<Block> GRASS_2 = REGISTRY.register("grass_2", () -> new Grass2Block());
	public static final RegistryObject<Block> GOLDENROD = REGISTRY.register("goldenrod", () -> new GoldenrodBlock());
	public static final RegistryObject<Block> FOURLEAF_CLOVER = REGISTRY.register("fourleaf_clover", () -> new FourleafCloverBlock());
	public static final RegistryObject<Block> FLOWER_6 = REGISTRY.register("flower_6", () -> new Flower6Block());
	public static final RegistryObject<Block> FLOWER_7 = REGISTRY.register("flower_7", () -> new Flower7Block());
	public static final RegistryObject<Block> SHADOW_FUNGUS = REGISTRY.register("shadow_fungus", () -> new ShadowFungusBlock());
	public static final RegistryObject<Block> GRASS_8 = REGISTRY.register("grass_8", () -> new Grass8Block());
	public static final RegistryObject<Block> GRASS_9 = REGISTRY.register("grass_9", () -> new Grass9Block());
	public static final RegistryObject<Block> GRASS_10 = REGISTRY.register("grass_10", () -> new Grass10Block());
	public static final RegistryObject<Block> GRASS_11 = REGISTRY.register("grass_11", () -> new Grass11Block());
	public static final RegistryObject<Block> GRASS_12 = REGISTRY.register("grass_12", () -> new Grass12Block());
	public static final RegistryObject<Block> FLOWER_15 = REGISTRY.register("flower_15", () -> new Flower15Block());
	public static final RegistryObject<Block> GRASS_13 = REGISTRY.register("grass_13", () -> new Grass13Block());
	public static final RegistryObject<Block> GRASS_14 = REGISTRY.register("grass_14", () -> new Grass14Block());
	public static final RegistryObject<Block> GRASS_15 = REGISTRY.register("grass_15", () -> new Grass15Block());
	public static final RegistryObject<Block> FLOWER_18 = REGISTRY.register("flower_18", () -> new Flower18Block());
	public static final RegistryObject<Block> FIG_VINE = REGISTRY.register("fig_vine", () -> new FigVineBlock());
	public static final RegistryObject<Block> MEMENTO_ITEM_11 = REGISTRY.register("memento_item_11", () -> new MementoItem11Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_0 = REGISTRY.register("structure_block_0", () -> new StructureBlock0Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_1 = REGISTRY.register("structure_block_1", () -> new StructureBlock1Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_2 = REGISTRY.register("structure_block_2", () -> new StructureBlock2Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_3 = REGISTRY.register("structure_block_3", () -> new StructureBlock3Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_4 = REGISTRY.register("structure_block_4", () -> new StructureBlock4Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_5 = REGISTRY.register("structure_block_5", () -> new StructureBlock5Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_6 = REGISTRY.register("structure_block_6", () -> new StructureBlock6Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_7 = REGISTRY.register("structure_block_7", () -> new StructureBlock7Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_8 = REGISTRY.register("structure_block_8", () -> new StructureBlock8Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_9 = REGISTRY.register("structure_block_9", () -> new StructureBlock9Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_10 = REGISTRY.register("structure_block_10", () -> new StructureBlock10Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_11 = REGISTRY.register("structure_block_11", () -> new StructureBlock11Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_12 = REGISTRY.register("structure_block_12", () -> new StructureBlock12Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_13 = REGISTRY.register("structure_block_13", () -> new StructureBlock13Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_14 = REGISTRY.register("structure_block_14", () -> new StructureBlock14Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_15 = REGISTRY.register("structure_block_15", () -> new StructureBlock15Block());
	public static final RegistryObject<Block> CLAYPAN_1 = REGISTRY.register("claypan_1", () -> new Claypan1Block());
	public static final RegistryObject<Block> CLAYPAN_2 = REGISTRY.register("claypan_2", () -> new Claypan2Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_16 = REGISTRY.register("structure_block_16", () -> new StructureBlock16Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_17 = REGISTRY.register("structure_block_17", () -> new StructureBlock17Block());
	public static final RegistryObject<Block> SHADOW_DUNGEON_DOOR_1 = REGISTRY.register("shadow_dungeon_door_1", () -> new ShadowDungeonDoor1Block());
	public static final RegistryObject<Block> TRUE_SHADOW_BED = REGISTRY.register("true_shadow_bed", () -> new TrueShadowBedBlock());
	public static final RegistryObject<Block> SHADOWDUNGEONDOOR_3 = REGISTRY.register("shadowdungeondoor_3", () -> new Shadowdungeondoor3Block());
	public static final RegistryObject<Block> AARONCOSHANDSPAWNBLOCK = REGISTRY.register("aaroncoshandspawnblock", () -> new AaroncoshandspawnblockBlock());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_18 = REGISTRY.register("structure_block_18", () -> new StructureBlock18Block());
	public static final RegistryObject<Block> ANGEL_BLOCK = REGISTRY.register("angel_block", () -> new AngelBlockBlock());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_19 = REGISTRY.register("structure_block_19", () -> new StructureBlock19Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_20 = REGISTRY.register("structure_block_20", () -> new StructureBlock20Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_21 = REGISTRY.register("structure_block_21", () -> new StructureBlock21Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_22 = REGISTRY.register("structure_block_22", () -> new StructureBlock22Block());
	public static final RegistryObject<Block> STRUCTURE_BLOCK_23 = REGISTRY.register("structure_block_23", () -> new StructureBlock23Block());
	public static final RegistryObject<Block> LIGHT_FIREFLY_GLASS_JAR = REGISTRY.register("light_firefly_glass_jar", () -> new LightFireflyGlassJarBlock());
	public static final RegistryObject<Block> DREAM_TRAIN_STRUCTURE = REGISTRY.register("dream_train_structure", () -> new DreamTrainStructureBlock());
	public static final RegistryObject<Block> WIND_KNIGHT_SPAWNBLOCK_1 = REGISTRY.register("wind_knight_spawnblock_1", () -> new WindKnightSpawnblock1Block());
	public static final RegistryObject<Block> WIND_KNIGHT_SPAWNBLOCK_2 = REGISTRY.register("wind_knight_spawnblock_2", () -> new WindKnightSpawnblock2Block());
	public static final RegistryObject<Block> WIND_KNIGHT_SPAWNBLOCK_3 = REGISTRY.register("wind_knight_spawnblock_3", () -> new WindKnightSpawnblock3Block());
	public static final RegistryObject<Block> WIND_KNIGHT_SPAWNBLOCK_4 = REGISTRY.register("wind_knight_spawnblock_4", () -> new WindKnightSpawnblock4Block());
	public static final RegistryObject<Block> SMALL_STONE_SPIRIT_BLOCK = REGISTRY.register("small_stone_spirit_block", () -> new SmallStoneSpiritBlockBlock());
}
